require("dotenv").config({ path: ".env.local" });
require("dotenv").config({ path: ".env.development.local" });
const fs = require("fs");
const path = require("path");
const { DatabaseSync } = require("node:sqlite");
const { Client } = require("pg");

// ============================================================
// CONFIGURATION
// ============================================================

const sqlitePath = path.join(
  process.cwd(),
  "data",
  "kazim-nawrozi.db"
);

// We will use the Neon/Vercel DATABASE_URL.
// IMPORTANT: do NOT put the actual password directly in this file.
const DATABASE_URL =
  process.env.KAZIM_NAWROZI_POSTGRES_URL ||
  process.env.KAZIM_NAWROZI_DATABASE_URL_UNPOOLED ||
  process.env.KAZIM_NAWROZI_DATABASE_URL ||
  process.env.DATABASE_URL_UNPOOLED ||
  process.env.DATABASE_URL ||
  process.env.POSTGRES_URL ||
  process.env.POSTGRES_URL_NON_POOLING;

if (!DATABASE_URL) {
  console.error(
    "\nERROR: PostgreSQL connection variable was not found."
  );

  console.error(
    "\nPlease make sure one of these environment variables exists:"
  );

  console.error("KAZIM_NAWROZI_POSTGRES_URL");
  console.error("KAZIM_NAWROZI_DATABASE_URL");

  process.exit(1);
}

if (!fs.existsSync(sqlitePath)) {
  console.error("\nERROR: SQLite database was not found:");
  console.error(sqlitePath);
  process.exit(1);
}

// ============================================================
// OPEN SQLITE
// ============================================================

console.log("\n========================================");
console.log(" Kazim Nawrozi → Neon Migration");
console.log("========================================\n");

console.log("SQLite database:");
console.log(sqlitePath);

const sqlite = new DatabaseSync(sqlitePath);

// ============================================================
// OPEN POSTGRES
// ============================================================

const pg = new Client({
  connectionString: DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});

async function main() {
  console.log("\nConnecting to Neon PostgreSQL...");

  await pg.connect();

  console.log("✓ Connected to Neon PostgreSQL\n");

  // ==========================================================
  // CREATE TABLES
  // ==========================================================

  console.log("Creating PostgreSQL tables...\n");

  await pg.query(`
    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      slug TEXT NOT NULL UNIQUE,
      description TEXT DEFAULT '',
      sort_order INTEGER NOT NULL DEFAULT 0,
      active INTEGER NOT NULL DEFAULT 1,
      last_login_at TIMESTAMP NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      category_id INTEGER NOT NULL,
      price DOUBLE PRECISION NOT NULL DEFAULT 0,
      size TEXT DEFAULT '',
      material TEXT DEFAULT '',
      dimensions TEXT DEFAULT '',
      origin TEXT DEFAULT '',
      weaving_method TEXT DEFAULT '',
      image TEXT DEFAULT '',
      images TEXT NOT NULL DEFAULT '[]',
      badge TEXT DEFAULT '',
      description TEXT DEFAULT '',
      stock INTEGER NOT NULL DEFAULT 0,
      sold INTEGER NOT NULL DEFAULT 0,
      new_arrival INTEGER NOT NULL DEFAULT 0,
      featured INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      legacy_category TEXT,
      FOREIGN KEY(category_id)
        REFERENCES categories(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
    );

    CREATE INDEX IF NOT EXISTS products_category_idx
      ON products(category_id);

    CREATE INDEX IF NOT EXISTS products_featured_idx
      ON products(featured);

    CREATE INDEX IF NOT EXISTS products_stock_idx
      ON products(stock, sold);


    CREATE TABLE IF NOT EXISTS admin_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      permissions TEXT NOT NULL DEFAULT '[]',
      active INTEGER NOT NULL DEFAULT 1,
      last_login_at TIMESTAMP NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS admin_users_active_idx
      ON admin_users(active);


    CREATE TABLE IF NOT EXISTS site_content (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      content_json TEXT NOT NULL DEFAULT '{}',
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


    CREATE TABLE IF NOT EXISTS mailing_list_subscribers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      status TEXT NOT NULL DEFAULT 'pending',
      approved_at TIMESTAMP NULL,
      email_sent_at TIMESTAMP NULL,
      delivery_error TEXT NOT NULL DEFAULT ''
    );


    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_number TEXT NOT NULL UNIQUE,
      customer_name TEXT NOT NULL,
      customer_email TEXT NOT NULL,
      phone TEXT NOT NULL,
      shipping_address TEXT NOT NULL DEFAULT '{}',
      delivery_method TEXT NOT NULL,
      delivery_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
      subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
      total DOUBLE PRECISION NOT NULL DEFAULT 0,
      payment_method TEXT NOT NULL DEFAULT 'cash_on_delivery',
      payment_status TEXT NOT NULL DEFAULT 'cod_pending',
      order_status TEXT NOT NULL DEFAULT 'new',
      notes TEXT DEFAULT '',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      tracking_token TEXT UNIQUE,
      whatsapp_opt_in INTEGER NOT NULL DEFAULT 0,
      advance_percent DOUBLE PRECISION,
      delivery_estimate TEXT NOT NULL DEFAULT '',
      deleted_at TIMESTAMP NULL
    );


    CREATE TABLE IF NOT EXISTS order_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL,
      product_id INTEGER NOT NULL,
      product_slug TEXT NOT NULL,
      product_name TEXT NOT NULL,
      unit_price DOUBLE PRECISION NOT NULL,
      quantity INTEGER NOT NULL,
      line_total DOUBLE PRECISION NOT NULL,
      advance_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
      delivery_region TEXT NOT NULL DEFAULT '',
      delivery_time TEXT NOT NULL DEFAULT '',
      FOREIGN KEY(order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,
      FOREIGN KEY(product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT
    );

    CREATE INDEX IF NOT EXISTS order_items_order_idx
      ON order_items(order_id);


    CREATE TABLE IF NOT EXISTS order_status_history (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL,
      status TEXT NOT NULL,
      actor_username TEXT NOT NULL DEFAULT 'system',
      note TEXT DEFAULT '',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS order_status_history_order_idx
      ON order_status_history(order_id, created_at);


    CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL,
      order_number TEXT NOT NULL,
      kind TEXT NOT NULL,
      recipient TEXT NOT NULL,
      subject TEXT NOT NULL,
      provider TEXT NOT NULL DEFAULT 'local',
      sent INTEGER NOT NULL DEFAULT 0,
      error TEXT DEFAULT '',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS notifications_order_idx
      ON notifications(order_id, created_at DESC);


    CREATE TABLE IF NOT EXISTS product_delivery_rules (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id INTEGER NOT NULL,
      region TEXT NOT NULL,
      advance_type TEXT NOT NULL DEFAULT 'none',
      advance_value DOUBLE PRECISION NOT NULL DEFAULT 0,
      delivery_time TEXT NOT NULL,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
    );


    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      actor_type TEXT NOT NULL DEFAULT 'staff',
      actor_id INTEGER,
      actor_username TEXT NOT NULL,
      action TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id INTEGER,
      details TEXT NOT NULL DEFAULT '{}',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS audit_logs_created_idx
      ON audit_logs(created_at DESC);

    CREATE INDEX IF NOT EXISTS audit_logs_actor_idx
      ON audit_logs(actor_id, actor_type);
  `);

  console.log("✓ PostgreSQL tables created\n");

  const sequenceTables = [
    "categories",
    "products",
    "product_delivery_rules",
    "admin_users",
    "site_content",
    "mailing_list_subscribers",
    "orders",
    "order_items",
    "order_status_history",
    "notifications",
    "audit_logs",
  ];

  for (const table of sequenceTables) {
    const column = await pg.query(
      `SELECT is_identity
       FROM information_schema.columns
       WHERE table_schema = current_schema()
         AND table_name = $1
         AND column_name = 'id'`,
      [table],
    );
    if (!column.rows[0]) {
      throw new Error(`Expected ${table}.id to exist after schema creation.`);
    }
    if (column.rows[0].is_identity !== "YES") {
      await pg.query(
        `ALTER TABLE "${table}" ALTER COLUMN id DROP DEFAULT;
         ALTER TABLE "${table}"
           ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`,
      );
    }
  }

  // ==========================================================
  // HELPER
  // ==========================================================

  async function migrateTable(table, columns) {
    const rows = sqlite
      .prepare(`SELECT ${columns.join(", ")} FROM ${table}`)
      .all();

    console.log(
      `${table}: ${rows.length} record(s)`
    );

    if (rows.length === 0) {
      return;
    }

    const columnList = columns.join(", ");

    const placeholders = columns
      .map((_, index) => `$${index + 1}`)
      .join(", ");

    const query = `
      INSERT INTO ${table} (${columnList})
      VALUES (${placeholders})
      ON CONFLICT DO NOTHING
    `;

    for (const row of rows) {
      const values = columns.map((column) => {
        const value = row[column];

        // Convert SQLite integer booleans to PostgreSQL-compatible
        // integers. We intentionally keep these as integers because
        // the existing application expects 0/1.
        return value;
      });

      await pg.query(query, values);
    }
  }

  // ==========================================================
  // MIGRATE IN FOREIGN-KEY ORDER
  // ==========================================================

  console.log("Starting data migration...\n");
  await pg.query("BEGIN");

  await migrateTable("categories", [
    "id",
    "name",
    "slug",
    "description",
    "sort_order",
    "active",
    "created_at",
    "updated_at",
  ]);

  await migrateTable("products", [
    "id",
    "slug",
    "name",
    "category_id",
    "price",
    "size",
    "material",
    "dimensions",
    "origin",
    "weaving_method",
    "image",
    "images",
    "badge",
    "description",
    "stock",
    "sold",
    "new_arrival",
    "featured",
    "created_at",
    "updated_at",
    "legacy_category",
  ]);

  await migrateTable("product_delivery_rules", [
    "id",
    "product_id",
    "region",
    "advance_type",
    "advance_value",
    "delivery_time",
    "updated_at",
  ]);

  await migrateTable("admin_users", [
    "id",
    "username",
    "password_hash",
    "permissions",
    "active",
    "last_login_at",
    "created_at",
    "updated_at",
  ]);

  await migrateTable("site_content", [
    "id",
    "content_json",
    "updated_at",
  ]);

  await migrateTable("mailing_list_subscribers", [
    "id",
    "email",
    "created_at",
    "updated_at",
    "status",
    "approved_at",
    "email_sent_at",
    "delivery_error",
  ]);

  await migrateTable("orders", [
    "id",
    "order_number",
    "customer_name",
    "customer_email",
    "phone",
    "shipping_address",
    "delivery_method",
    "delivery_fee",
    "subtotal",
    "total",
    "payment_method",
    "payment_status",
    "order_status",
    "notes",
    "created_at",
    "updated_at",
    "tracking_token",
    "whatsapp_opt_in",
    "advance_percent",
    "delivery_estimate",
    "deleted_at",
  ]);

  await migrateTable("order_items", [
    "id",
    "order_id",
    "product_id",
    "product_slug",
    "product_name",
    "unit_price",
    "quantity",
    "line_total",
    "advance_amount",
    "delivery_region",
    "delivery_time",
  ]);

  await migrateTable("order_status_history", [
    "id",
    "order_id",
    "status",
    "actor_username",
    "note",
    "created_at",
  ]);

  await migrateTable("notifications", [
    "id",
    "order_id",
    "order_number",
    "kind",
    "recipient",
    "subject",
    "provider",
    "sent",
    "error",
    "created_at",
  ]);

  await migrateTable("audit_logs", [
    "id",
    "actor_type",
    "actor_id",
    "actor_username",
    "action",
    "entity_type",
    "entity_id",
    "details",
    "created_at",
  ]);

  // ==========================================================
  // RESET POSTGRES SEQUENCES
  // ==========================================================

  console.log("\nResetting PostgreSQL sequences...\n");

  for (const table of sequenceTables) {
    const max = await pg.query(`SELECT MAX(id) AS max_id FROM "${table}"`);
    const sequence = await pg.query(
      "SELECT pg_get_serial_sequence($1, 'id') AS name",
      [table],
    );
    const sequenceName = sequence.rows[0].name;
    if (!sequenceName) {
      throw new Error(`Could not find the PostgreSQL identity for ${table}.id.`);
    }
    const maxId = max.rows[0].max_id;
    await pg.query(
      "SELECT setval($1::regclass, $2, $3)",
      [sequenceName, maxId ?? 1, maxId !== null],
    );
  }

  // ==========================================================
  // VERIFY COUNTS
  // ==========================================================

  console.log("\n========================================");
  console.log(" Migration Verification");
  console.log("========================================\n");

  const tables = [
    "admin_users",
    "audit_logs",
    "categories",
    "mailing_list_subscribers",
    "notifications",
    "order_items",
    "order_status_history",
    "orders",
    "product_delivery_rules",
    "products",
    "site_content",
  ];

  let allGood = true;

  for (const table of tables) {
    const sqliteResult = sqlite
      .prepare(`SELECT COUNT(*) AS count FROM ${table}`)
      .get();

    const pgResult = await pg.query(
      `SELECT COUNT(*) AS count FROM ${table}`
    );

    const sqliteCount = Number(sqliteResult.count);
    const pgCount = Number(pgResult.rows[0].count);

    const status =
      sqliteCount === pgCount ? "✓" : "✗";

    console.log(
      `${status} ${table}: SQLite=${sqliteCount} PostgreSQL=${pgCount}`
    );

    if (sqliteCount !== pgCount) {
      allGood = false;
    }
  }

  console.log("\n========================================");

  if (allGood) {
    await pg.query("COMMIT");
    console.log("✓ MIGRATION SUCCESSFUL");
    console.log("========================================\n");
    console.log(
      "All SQLite records were successfully copied to Neon PostgreSQL."
    );
  } else {
    await pg.query("ROLLBACK");
    console.log("✗ MIGRATION HAS COUNT MISMATCHES");
    console.log("========================================\n");
    console.log(
      "Do NOT switch the application to PostgreSQL yet."
    );
  }

  await pg.end();
  sqlite.close();

  process.exit(allGood ? 0 : 1);
}

main().catch(async (error) => {
  console.error("\n========================================");
  console.error("MIGRATION ERROR");
  console.error("========================================\n");

  console.error(error);

  try {
    await pg.end();
  } catch {}

  try {
    sqlite.close();
  } catch {}

  process.exit(1);
});