'use client';
import {useEffect,useMemo,useState} from 'react';
import AdminShell from '@/components/AdminShell';

const rights=[['store','Store / Products'],['inventory','Inventory'],['orders','Orders'],['categories','Categories'],['analytics','Analytics'],['settings','Settings'],['delivery','Delivery Methods'],['policies','Store Policies']] as const;
type U={id?:number;username:string;password?:string;permissions:string[];active:number;last_login_at?:string|null;created_at?:string;updated_at?:string};
type Log={id:number;actor_username:string;action:string;entity_type:string;entity_id:number|null;details:any;created_at:string};
const blank:U={username:'',password:'',permissions:[],active:1};
function fmt(v?:string|null){return v?new Date(v).toLocaleString():'Never'}
export default function Users(){
 const [u,setU]=useState<U>(blank),[list,setList]=useState<U[]>([]),[logs,setLogs]=useState<Log[]>([]),[error,setError]=useState(''),[ok,setOk]=useState(''),[editing,setEditing]=useState(false),[tab,setTab]=useState<'users'|'audit'>('users'),[search,setSearch]=useState('');
 async function load(){const r=await fetch('/api/admin/users',{cache:'no-store'});if(r.ok){const d=await r.json();setList(d.users||[]);setLogs(d.logs||[])}}
 useEffect(()=>{load()},[]);
 function toggle(p:string){setU(x=>({...x,permissions:x.permissions.includes(p)?x.permissions.filter(a=>a!==p):[...x.permissions,p]}))}
 function edit(x:U){setU({...x,password:''});setEditing(true);setError('');setOk('');window.scrollTo({top:0,behavior:'smooth'})}
 function cancel(){setU(blank);setEditing(false);setError('');setOk('')}
 async function save(){setError('');setOk('');const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(u)});const d=await r.json();if(!r.ok)setError(d.error||'Unable to save');else{setOk(editing?'User updated.':'User created.');cancel();await load()}}
 async function toggleActive(id:number){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'toggle'})});if(!r.ok){const d=await r.json();setError(d.error||'Unable to change status')}await load()}
 async function resetPassword(id:number){const p=prompt('Enter a new temporary password (minimum 8 characters):');if(!p)return;const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'reset_password',password:p})});const d=await r.json();if(!r.ok)setError(d.error||'Unable to reset password');else{setOk('Password reset successfully.');await load()}}
 const filtered=useMemo(()=>list.filter(x=>x.username.toLowerCase().includes(search.toLowerCase())),[list,search]);
 return <AdminShell>
  <div><p className="text-xs uppercase tracking-[.25em] text-[var(--terracotta)]">Access control</p><h1 className="mt-2 text-4xl">Admin users</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Manage staff accounts, permissions, passwords, account status and the audit trail for administrative activity.</p></div>
  <div className="mt-8 flex gap-2 border-b border-[var(--line)]"><button onClick={()=>setTab('users')} className={`px-4 py-3 text-sm ${tab==='users'?'border-b-2 border-[var(--charcoal)] font-semibold':''}`}>Users</button><button onClick={()=>setTab('audit')} className={`px-4 py-3 text-sm ${tab==='audit'?'border-b-2 border-[var(--charcoal)] font-semibold':''}`}>Activity / Audit Log</button></div>
  {tab==='users'?<>
   <section className="mt-6 border border-[var(--line)] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-2xl">{editing?'Edit staff user':'Create staff user'}</h2><p className="mt-1 text-sm text-[var(--muted)]">Passwords are stored as secure scrypt hashes. Staff cannot grant themselves the Admin Users permission.</p></div>{editing&&<button onClick={cancel} className="border px-4 py-2 text-sm">Cancel edit</button>}</div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm">Username<input className="mt-2 w-full border border-[var(--line)] p-3" value={u.username} onChange={e=>setU({...u,username:e.target.value})} placeholder="storemanager"/></label><label className="text-sm">{editing?'New password (leave blank to keep current)':'Password'}<input className="mt-2 w-full border border-[var(--line)] p-3" type="password" value={u.password||''} onChange={e=>setU({...u,password:e.target.value})} placeholder="Minimum 8 characters"/></label></div>
    {editing&&<label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={u.active===1} onChange={e=>setU({...u,active:e.target.checked?1:0})}/> Account enabled</label>}
    <p className="mt-5 text-sm font-semibold">Permissions</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{rights.map(([key,label])=><label key={key} className="flex items-center gap-3 border p-3 text-sm"><input type="checkbox" checked={u.permissions.includes(key)} onChange={()=>toggle(key)}/>{label}</label>)}</div>
    {error&&<p className="mt-4 text-sm text-red-700">{error}</p>}{ok&&<p className="mt-4 text-sm text-green-700">{ok}</p>}
    <button onClick={save} className="mt-5 bg-[var(--charcoal)] px-5 py-3 text-sm text-white">{editing?'Save Changes':'Create User'}</button>
   </section>
   <section className="mt-6 border border-[var(--line)] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-2xl">Staff accounts</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search username" className="border border-[var(--line)] px-3 py-2 text-sm"/></div>
    <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr className="border-b border-[var(--line)]"><th className="p-3">User</th><th className="p-3">Permissions</th><th className="p-3">Status</th><th className="p-3">Last login</th><th className="p-3">Created</th><th className="p-3">Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-b border-[var(--line)] last:border-0"><td className="p-3 font-medium">{x.username}</td><td className="max-w-[300px] p-3 text-xs text-[var(--muted)]">{x.permissions.length?x.permissions.join(' · '):'No permissions'}</td><td className="p-3">{x.active?<span className="text-green-700">Active</span>:<span className="text-red-700">Disabled</span>}</td><td className="p-3 text-xs">{fmt(x.last_login_at)}</td><td className="p-3 text-xs">{fmt(x.created_at)}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={()=>edit(x)} className="border px-3 py-2">Edit</button><button onClick={()=>resetPassword(x.id!)} className="border px-3 py-2">Reset Password</button><button onClick={()=>toggleActive(x.id!)} className="border px-3 py-2">{x.active?'Disable':'Enable'}</button></div></td></tr>)}</tbody></table></div>
   </section>
  </>:<section className="mt-6 border border-[var(--line)] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-2xl">Activity / Audit Log</h2><p className="mt-1 text-sm text-[var(--muted)]">Administrative actions are recorded locally in SQLite.</p></div><button onClick={load} className="border px-4 py-2 text-sm">Refresh</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[var(--line)]"><th className="p-3">Date / Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Entity</th><th className="p-3">Details</th></tr></thead><tbody>{logs.map(l=><tr key={l.id} className="border-b border-[var(--line)] last:border-0"><td className="p-3 text-xs">{fmt(l.created_at)}</td><td className="p-3">{l.actor_username}</td><td className="p-3 font-medium">{l.action}</td><td className="p-3">{l.entity_type}{l.entity_id?` #${l.entity_id}`:''}</td><td className="max-w-[400px] p-3 text-xs text-[var(--muted)]">{Object.keys(l.details||{}).length?JSON.stringify(l.details):'—'}</td></tr>)}{logs.length===0&&<tr><td colSpan={5} className="p-8 text-center text-sm text-[var(--muted)]">No activity recorded yet.</td></tr>}</tbody></table></div></section>}
 </AdminShell>
}
